export default {
  REQUEST_SIGNIN: "REQUEST_SIGNIN",
  REQUEST_SIGNOUT: "REQUEST_SIGNOUT",
  REQUEST_SIGNUP: "REQUEST_SIGNUP",

  REQUEST_ADMIN_SIGNIN: "REQUEST_ADMIN_SIGNIN",

  AUTH_CHECK: "AUTH_CHECK",
  AUTH_LOGIN: "AUTH_LOGIN",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_REFRESH_TOKEN: "AUTH_REFRESH_TOKEN",

  REQUEST_FORGOT_PASSWORD: "REQUEST_FORGOT_PASSWORD",
  REQUEST_RESET_PASSWORD: "REQUEST_RESET_PASSWORD",

  AUTH_RESET_PASSWORD: "AUTH_RESET_PASSWORD",
  AUTH_USER: "AUTH_USER",

  REQUEST_VERIFY_EMAIL: "REQUEST_VERIFY_EMAIL",
  REQUEST_VERIFY_PHONE: "REQUEST_VERIFY_PHONE",

  REQUEST_CUSTOMER_SIGNUP: "REQUEST_CUSTOMER_SIGNUP",
  REQUEST_SUPPLIER_SIGNUP: "REQUEST_SUPPLIER_SIGNUP",
  REQUEST_SERVICEPROVIDER_SIGNUP: "REQUEST_SERVICEPROVIDER_SIGNUP",

  VERIFY_EMAIL: "VERIFY_EMAIL",
  VERIFY_PHONE: "VERIFY_PHONE",

  REQUEST_SOCIAL_SIGNUP: "REQUEST_SOCIAL_SIGNUP",
  REQUEST_SOCIAL_SIGNIN: "REQUEST_SOCIAL_SIGNIN",

  INIT_AUTH: "INIT_AUTH",

  RESEND_EMAIL_VERIFICATION: "RESEND_EMAIL_VERIFICATION",
  RESEND_PHONE_VERIFICATION: "RESEND_PHONE_VERIFICATION",

  AUTH_USER_TYPE: "AUTH_USER_TYPE",
  AUTH_TEMP_USER_TYPE: "AUTH_TEMP_USER_TYPE",
};
